apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2019-04-09T12:35:21Z
  generation: 2
  labels:
    k8s-app: gotrial
  name: gotrial
  namespace: default
  resourceVersion: "24524"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gotrial
  uid: f0bfcfb7-5ac3-11e9-8d57-06ba7a51dd2d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: gotrial
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: gotrial
      name: gotrial
    spec:
      containers:
      - image: kiranjain2/mydockerimage:1
        imagePullPolicy: Always
        name: gotrial
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-04-09T12:36:39Z
    lastUpdateTime: 2019-04-09T12:36:39Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-04-09T12:35:21Z
    lastUpdateTime: 2019-04-09T12:36:39Z
    message: ReplicaSet "gotrial-65fc888869" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1