apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-04-09T09:02:47Z
  generation: 1
  labels:
    k8s-app: bordered
  name: bordered
  namespace: default
  resourceVersion: "4595"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bordered
  uid: 3e8b0357-5aa6-11e9-8d57-06ba7a51dd2d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: bordered
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: bordered
      name: bordered
    spec:
      containers:
      - image: nodered/node-red-docker
        imagePullPolicy: Always
        name: bordered
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-04-09T09:03:16Z
    lastUpdateTime: 2019-04-09T09:03:16Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-04-09T09:02:47Z
    lastUpdateTime: 2019-04-09T09:03:16Z
    message: ReplicaSet "bordered-856b4bdf8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
